import numpy as np
from general_segmentation_functions.image_handling import view_napari, get_image, save_image
from general_segmentation_functions.image_processing import insert_array,draw_ellipsoid,trim_zeros
from scipy.ndimage import distance_transform_edt
from pathlib import Path
import random

def create_ordered_test():
    img_shape = [60,2000,2000]
    ball_shapes = [40,400,400]

    img = np.zeros(img_shape)

    def create_fake_ball(shape):
        # Create a small numpy array of a 2D/3D ball of a supplied shape that resembles a cell in the image
        # Intensity values are generated by a simple EDT where the center is brighter than the border
        radius = [i/2 for i in shape]
        if len(radius)==2:
            radius=[0]+radius
        ball=draw_ellipsoid(radius, remove_border_zeros=False).astype("float32")
        edt = distance_transform_edt(
            ball
            )
        edt = edt / np.max(edt)
        ball *= (0.6 + 0.4*edt)
        ball = trim_zeros(ball)
        return(ball)

    x_coordinates = np.full([3,3], img_shape[2])
    y_coordinates = np.full([3,3], img_shape[1])
    z_coordinates = np.full([3,3], img_shape[0])


    x_settings=np.array([
        [0.25, 0.5, 0.75],
        [0.25, 0.5, 0.75],
        [0.25, 0.5, 0.75]
    ])

    y_settings=np.array([
        [0.25, 0.25, 0.25],
        [0.5, 0.5, 0.5],
        [0.75, 0.75, 0.75]
    ])

    x_coordinates = (x_coordinates * x_settings).astype('int64')
    y_coordinates = (y_coordinates * y_settings).astype('int64')
    z_coordinates = (0.5 * z_coordinates).astype('int64')

    coords = []
    for i in range(3):
        row = []
        for j in range(3):
            values = [z_coordinates[i, j], y_coordinates[i, j], x_coordinates[i, j]]
            coords.append(values)

    ball = create_fake_ball(ball_shapes)

    for coord in coords: 
        img = insert_array(img, ball, coords_center=coord)
        
    save_image(img, "/Users/samdeblank/Documents/1.projects/Zipping/test_image.tiff")
    


def create_round_segments(shape, min_diameter, max_diameter, element_sizes):
    array = np.zeros(shape, dtype=int)
    
    num_segments = random.randint(100, 120)  # Adjust the number of segments as needed
    
    for segment_num in range(num_segments):
        diameter = random.randint(min_diameter, max_diameter)
        
        # Ensure valid ranges for starting positions
        x = random.randint(0, max(0, (shape[0] - diameter) // element_sizes[0]))
        y = random.randint(0, max(0, shape[1] - diameter))
        z = random.randint(0, max(0, shape[2] - diameter))

        for i in range(diameter):
            for j in range(diameter):
                for k in range(diameter):
                    xi = x * element_sizes[0] + i
                    yi = y + j
                    zi = z + k
                    if xi < shape[0] and yi < shape[1] and zi < shape[2] and \
                        ((i - diameter // 2) ** 2 + (j - diameter // 2) ** 2 + (k - diameter // 2) ** 2) <= (diameter // 2) ** 2:
                        array[xi, yi, zi] = (segment_num + 1) * 100  # Unique number for each segment

    return array

# Define the shape of the 3D array
shape = (120, 4000, 4000)

# Define the minimum and maximum diameter of the round segments
min_diameter = 40
max_diameter = 60

# Define the element sizes
element_sizes = (4, 1, 1)

# Create the 3D numpy array with round segments
result_array = create_round_segments(shape, min_diameter, max_diameter, element_sizes)
save_image(result_array, path="/Users/malieva/Desktop/test_image_big.tiff")

# Display the shape of the resulting array
print("Shape of the array:", result_array.shape)



# Display the shape of the resulting array
print("Shape of the array:", result_array.shape)
